const giochiPokemon = [
    { value: 1, label: 'Rosso' },
    { value: 2, label: 'Blu' },
    { value: 3, label: 'Giallo' },
    { value: 4, label: 'Verde' },
    { value: 5, label: 'Oro' },
    { value: 6, label: 'Argento' },
    { value: 7, label: 'Cristallo' },
    { value: 8, label: 'Rubino' },
    { value: 9, label: 'Zaffiro' },
    { value: 10, label: 'Smeraldo' },
    { value: 11, label: 'Rosso Fuoco (remake)' },
    { value: 12, label: 'Verde Foglia (remake)' },
    { value: 13, label: 'Diamante' },
    { value: 14, label: 'Perla' },
    { value: 15, label: 'Platino' },
    { value: 16, label: 'Oro HeartGold' },
    { value: 17, label: 'Argento SoulSilver' },
    { value: 18, label: 'Nero' },
    { value: 19, label: 'Bianco' },
    { value: 20, label: 'Nero 2' },
    { value: 21, label: 'Bianco 2' },
    { value: 22, label: 'X' },
    { value: 23, label: 'Y' },
    { value: 24, label: 'Rubino Omega' },
    { value: 25, label: 'Zaffiro Alpha' },
    { value: 26, label: 'Sole' },
    { value: 27, label: 'Luna' },
    { value: 28, label: 'Ultrasole' },
    { value: 29, label: 'Ultraluna' },
    { value: 30, label: 'Spada' },
    { value: 31, label: 'Scudo' },
    { value: 32, label: 'Brillante Diamante' },
    { value: 33, label: 'Lucente Perla' },
    { value: 34, label: 'Leggende Pokémon: Arceus' },
];
export {giochiPokemon};